### ISSUE TITLE
Maximum call stack exceeded

### ISSUE THREAD

**Issue by thelgevold** [robwormald/ng2-compiler-test2#2]
Hi,

I am not sure if this project is maintained or current, but I tried to build it and got the following error after doing `npm run build`

> ng2-compiler-test2@1.0.0 _compile:es5 /Users/helgevot/development/ng2-compiler-test2
> tsc tmp/build.js --target es5 --allowJs --outDir dist

/Users/helgevot/development/ng2-compiler-test2/node_modules/typescript/lib/tsc.js:35885
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at checkExpression (/Users/helgevot/development/ng2-compiler-test2/node_modules/typescript/lib/tsc.js:22217:33)
    at getContextualTypeForBinaryOperand (/Users/helgevot/development/ng2-compiler-test2/node_modules/typescript/lib/tsc.js:19579:28)
    at getContextualType (/Users/helgevot/development/ng2-compiler-test2/node_modules/typescript/lib/tsc.js:19719:28)
    at getApparentTypeOfContextualType (/Users/helgevot/development/ng2-compiler-test2/node_modules/typescript/lib/tsc.js:19689:24)
    at checkArrayLiteral (/Users/helgevot/development/ng2-compiler-test2/node_modules/typescript/lib/tsc.js:19833:38)
    at checkExpressionWorker (/Users/helgevot/development/ng2-compiler-test2/node_modules/typescript/lib/tsc.js:22264:28)
    at checkExpression (/Users/helgevot/development/ng2-compiler-test2/node_modules/typescript/lib/tsc.js:22223:42)
    at checkExpressionCached (/Users/helgevot/development/ng2-compiler-test2/node_modules/typescript/lib/tsc.js:22183:38)
    at /Users/helgevot/development/ng2-compiler-test2/node_modules/typescript/lib/tsc.js:14961:107
    at Object.map (/Users/helgevot/development/ng2-compiler-test2/node_modules/typescript/lib/tsc.js:178:29)
    at getTypeOfVariableOrParameterOrProperty (/Users/helgevot/development/ng2-compiler-test2/node_modules/typescript/lib/tsc.js:14961:57)

Using TypeScript 1.9.0-dev.20160607-1.0

**Comment by thelgevold** [comment]
It appears that this is failing because of the liberal versioning in package.json

The following configuration will build. I locked down the versions and added the missing ugligy.js

```
"dependencies": {
    "@angular/common": "2.0.0-rc.1",
    "@angular/compiler": "2.0.0-rc.1",
    "@angular/compiler-cli": "0.2.0",
    "@angular/core": "2.0.0-rc.1",
    "@angular/platform-browser": "2.0.0-rc.1",
    "@angular/platform-server": "2.0.0-rc.1",
    "rollup-plugin-node-resolve": "1.5.0",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.27",
    "typescript": "1.9.0-dev.20160429",
    "uglifyjs": "2.4.10",
    "zone.js": "0.6.6"
  },
  "devDependencies": {
    "rollup": "0.26.1",
    "rxjs-es": "5.0.0-beta.6"
  }
```
